# Generated by Django 5.0.6 on 2024-07-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_pointofview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofview',
            name='news',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pointofview', to='news.news'),
            preserve_default=False,
        ),
    ]
