# Generated by Django 5.0.6 on 2024-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_coler_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='coler',
            field=models.CharField(default='##86e2f4', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='coler_text',
            field=models.CharField(default='#ffff', max_length=500),
        ),
    ]
