# Generated by Django 5.0.6 on 2024-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_coler_alter_category_coler_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='coler',
            field=models.CharField(default='##f5f5f5', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='coler_text',
            field=models.CharField(default='#333', max_length=500),
        ),
    ]
