# Generated by Django 5.0.6 on 2024-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_category_coler_alter_category_coler_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='coler_text',
            new_name='color_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='coler',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#f5f5f5', max_length=500),
        ),
    ]
