# Generated by Django 5.0.6 on 2024-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_coler_text_category_color_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status_news',
            field=models.IntegerField(choices=[(0, 'در حال انتظار'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_text',
            field=models.CharField(default='#000', max_length=500),
        ),
    ]
