# Generated by Django 5.0.6 on 2024-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_status_news_alter_category_color_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
