# Generated by Django 5.0.6 on 2024-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofview',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
