# Generated by Django 5.0.6 on 2024-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status_author',
            field=models.IntegerField(choices=[(0, 'در حال انتظار'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
    ]
