# Generated by Django 5.0.6 on 2024-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_author_user_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
