# Generated by Django 5.0.6 on 2024-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_author_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.CharField(default='YYYY/MM/DD', max_length=20),
        ),
    ]
