# Generated by Django 5.0.6 on 2024-06-30 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_and_last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('hours_of_work', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactussettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=200)),
                ('name_site', models.CharField(max_length=200)),
                ('telegram_url', models.CharField(max_length=200)),
                ('instagram_url', models.CharField(max_length=200)),
                ('whatsapp_url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('copy_right', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('logo_favicon', models.FileField(blank=True, upload_to='logo_favicon')),
                ('logo_header', models.FileField(blank=True, upload_to='logo_header')),
                ('logo_header_dark', models.FileField(blank=True, upload_to='logo_header_dark')),
                ('logo_header_menu', models.FileField(blank=True, upload_to='logo_header_menu')),
                ('logo_header_menu_dark', models.FileField(blank=True, upload_to='logo_header_menu_dark')),
                ('logo_footer', models.FileField(blank=True, upload_to='logo_footer')),
                ('site_title', models.TextField(blank=True, null=True)),
                ('footer_title', models.TextField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
